### ISSUE TITLE
Installation Description de/en is missing chmod for cache logs uploads xmlschemas

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#114]
**Describe the bug**
In the documentation the chmod commands are missing.
see https://doc.mapbender.org/en/installation/installation_ubuntu.html

The commands were in the documentation in version 3.5. Please have a look if needed.

https://docs.mapbender.org/3.0.5/de/book/installation/installation_ubuntu.html

```
sudo chmod -R ug+w /var/www/mapbender/app/cache
sudo chmod -R ug+w /var/www/mapbender/app/logs
sudo chmod -R ug+w /var/www/mapbender/web/uploads
```

**Versions (in which version of the documentation does the error occur):**
 - Mapbender: 3.0.8.x

**Improvement**
Please add the links to the documentation

**Comment by fhaefker** [comment]
Hello @astroidex

Thanks for the comment.

However, the folder has already been "passed" to the "Apache user", thus the chmod commands are no longer required.

Kind regards
