### ISSUE TITLE
missing documentation - properties for your “sidepane” region

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender-documentation#133]
**Describe the bug**
There is no understandable documentation for the display options in the sidepane. The three options  (none, tabs, accordion) are only mentioned in the documentation "how to create templates".
New user can’t know how to change the look of the sidepane without a proper documentation of these buttons : ) 

Link to the bug:
* in the documentation https://doc.mapbender3.org/en/customization/templates.html?#adding-properties-for-your-sidepane-region

**Versions (in which version of the documentation does the error occur):**
 - Mapbender: all versions

**Improvement**
A clear description of the three options with a screenshot of the behaviour in the application, e.g. as a new side "sidepane" under https://doc.mapbender3.org/en/functions/backend.html ? 

**Screenshots**

![Auswahl_005](https://user-images.githubusercontent.com/13517141/69272046-419df800-0bd6-11ea-909f-8a702346db7d.png)

**Comment by AxxL** [comment]
The magenta colored highlighting box brought me here. :D I suggest: https://doc.mapbender3.org/de/customization/mapbender_templates.html since it's template related. But that are only my 5 cents.

**Comment by rschwammborn** [comment]
Hi! More in-depth instructions to the sidepane were added/will be added to the documentation. See #172 & #192
