### ISSUE TITLE
Missing icons and design elements - tip to see everything

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender-documentation#139]
**Describe your feature request**
With Mapbender, the different calls in the browser can cause the incorrect display of characters and missing design parts. Reason is usually (as far as i know) that in different calls different contents are pre-stored in the cache.
The call with app_dev.php therefore does not contain any missing elements.

**Additional context**
Trigger is (as far as i know) that you open Mapbender with "app.php" and without this 
 with "https://servername/mapbender" or for developer with "https://servername/mapbender/app_dev.php" 
-> don’t use "https://servername/mapbender/app.php".
Maybe a bug from Mapbender? Happens often.

Solution: Clear cache folder. Delete mapbender/app/cache/prod and mapbender/app/cache/dev. In a private browser window you probably see everything directly.

Perhaps we could add this information in https://doc.mapbender.org/en/customization.html or https://doc.mapbender.org/en/faq.html ? 

**Screenshots**

![mapbender](https://user-images.githubusercontent.com/13517141/69793173-38a9b980-11c8-11ea-8b4c-37163cb95a46.jpg)

**Comment by rschwammborn** [comment]
Could, if necessary, be implemented in FAQ (https://doc.mapbender.org/en/faq.html#app-php-und-app-dev-php-what-purpose-do-they-have). Nevertheless, I think should be enough to give basic cache deletion usage tips (as already documented, see link).
