### ISSUE TITLE
Documentation of supported formats of WMS-requests

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender-documentation#145]
**Describe your feature request**
You can define the formats for each request of the wms-instance in your application. There you can e.g. say that your map request is in format image/png. But the supported formats are not listed in any page of the documentation.

Error, that happens often: New users can't understand, why the wms-instance is not displayed in the map, when the default value for the format is image/bmp (only example). 

Solution: 
Documentation for each request: 
* Supported formats for getMap-Request: image/png, image/jpeg
* Supported formats for GetFeatureInfo-Request: text/html, text/plain
* ...

Perhaps this can be added here: https://doc.mapbender.org/en/functions/backend/layerset.html#layerset-instances

**Screenshots**

Wrong: 
![wms_einbindung_mapbender_falsch](https://user-images.githubusercontent.com/13517141/70606538-fab38900-1bfc-11ea-9b48-bca074832413.png)

Right: 
![wms_einbindung_mapbender_richtig](https://user-images.githubusercontent.com/13517141/70606544-fdae7980-1bfc-11ea-8252-ed1c8167b499.png)

**Comment by rschwammborn** [comment]
The example was already altered to a screenshot that shows image/png and text/html.
I made a PR #164 & included a hint that you are also allowed to use text/plain as format type.
