### ISSUE TITLE
[layertree][YAML] add information about how to define thematic layertree via YAML definition

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#146]
**Describe your feature request**
Layertree add information about how to define thematic layertree via YAML definition

The documentation could be integrated in 
https://doc.mapbender.org/en/customization/yaml.html
or https://doc.mapbender.org/en/functions/basic/layertree.html

**Comment by thzanger** [comment]
Closure was a mistake on my part. Issue still relevant.

**Comment by astroidex** [comment]
Done at page https://doc.mapbender.org/en/functions/basic/layertree.html
