### ISSUE TITLE
Change documentation for cookieconsent - add in formation about mapbender.cookieconsent: true

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#147]
**Describe the bug**
Looks the Cookie Consens Configuration changed with version 3.0.8.x.
https://doc.mapbender.org/de/functions/backend/cookieconsent.html#konfiguration
Does not work anymore

Instead you have to define in parameters.yml 

`    mapbender.cookieconsent: true`

Looks like you can't configure the cookieconsent as describe in config.yml. Please find out whether there is still a way to configure it.

Link to the bug if possible:
* https://doc.mapbender.org/de/functions/backend/cookieconsent.html#konfiguration

**Versions (in which version of the documentation does the error occur):**
 - Mapbender: 3.0.8.4

**Improvement**
Please update the documentation.

Would be great to have the parameter **mapbender.cookieconsent** also added to parameters.yml.dist so people will know about it.

https://github.com/mapbender/mapbender-starter/blob/master/application/app/config/parameters.yml.dist

**Comment by rschwammborn** [comment]
Hey @astroidex, I created a pull request: #150 
AFAIK, there is no way to set the configuration of the cookie consent message via config.yml anymore.
Moreover, the documentation should be the right place to make users aware of the implementation of the cookie banner (according to our developers).

**Comment by rschwammborn** [comment]
Hey @astroidex , thanks for pointing out the cookie issue! Your suggestions were implemented in the documentation via #150. I'm closing this issue now.
