### ISSUE TITLE
Installation descripition app/console fom:user:resetroot is missing

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#159]
When you create a database from scratch you have to run the command to create an admin user

`app/console fom:user:resetroot`

This information is missin in the documentation at 

https://doc.mapbender.org/en/installation/installation_ubuntu.html
-> Initialisation of the database connection:

It was still there in version 3.0.6 see:  https://docs.mapbender.org/3.0.6/en/book/installation/installation_ubuntu.html#id1

**Comment by eschuettler** [comment]
Hello,

The information was deleted on purpose, because it was redundant. 

A very detailed description can be found here: https://doc.mapbender.org/de/installation/configuration.html#erzeugen-des-administrativen-benutzers.
The link is also in the documentation on installation.

Kind regards
