### ISSUE TITLE
app/console mapbender:source:rewrite:host add parameter information

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#173]
**Describe your feature request**
app/console mapbender:source:rewrite can earily replace hosts. But in the ducumentation the order is not clear.

In the help it says:
app/console mapbender:source:rewrite --help
```
Usage:
  mapbender:source:rewrite:host [options] [--] <from> <to>

Arguments:
  from
  to
```
https://doc.mapbender.org/en/customization/commands.html#app-console-mapbender-source-rewrite-host

Please add this information about the parameter ordering to the documentation

`app/console mapbender:source:rewrite:host <from> <to>`

**Comment by rschwammborn** [comment]
In my opinion, this should be common sense. Therefore, it shouldn't explicitly be documented in Mapbender documentation. Help via command line (with `--help`) should be enough for users who use Mapbender commands to re-read the parameter order if unclear.
