### ISSUE TITLE
Installation with PostgreSQL missing resetroot and newway to load epsg codes

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#175]
**Describe the bug**
In the describtion on how to run Mapbender with PostgreSQL database the following row is missing. It is needed to create the admin user.

app/console fom:user:resetroot

https://doc.mapbender.org/en/installation/installation_ubuntu.html#optional

It was still there in version 3.0.7
https://docs.mapbender.org/3.0.7/en/installation/installation_ubuntu.html#id1

**Versions (in which version of the documentation does the error occur):**
 - Mapbender: 3.0.8.5

**Improvement**

- Please add the row to en/de and windows/ubuntu installation page
- Also use the new way to load epsg-Code: app/console mapbender:database:init -v

Block with comments
```
cd /var/www/mapbender
app/console doctrine:database:create
app/console doctrine:schema:create
app/console fom:user:resetroot
CAN BE REMOVED app/console assets:install web --symlink --relative
OLD VERSION app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Epsg/ --append
REPLACE WITH app/console mapbender:database:init -v
app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append
```
New definition
```
cd /var/www/mapbender
app/console doctrine:database:create
app/console doctrine:schema:create
app/console fom:user:resetroot
app/console mapbender:database:init -v
app/console doctrine:fixtures:load --fixtures=./mapbender/src/Mapbender/CoreBundle/DataFixtures/ORM/Application/ --append
```

**Comment by rschwammborn** [comment]
Connected PR, not completely ready for merge: https://github.com/mapbender/mapbender-documentation/pull/188

**Comment by rschwammborn** [comment]
The connected PR has now been merged. It takes some of your suggestions into account: The new way to load EPSG-codes is now integrated. Resetting the root account has not been implemented into the installation files, because it's a database operation and is already documented in the installation-configuration-file (Keyword: clutter-reducing, see documentation in e.g. https://github.com/mapbender/mapbender-documentation/blob/master/en/installation/configuration.rst).

**Comment by astroidex** [comment]
Hi @rschwammborn, please add the row to the installation as many user get confused when after installation the root user is not there and you can not login. 

`app/console fom:user:resetroot`

It is great that we have the detailed description here  https://github.com/mapbender/mapbender-documentation/blob/master/en/installation/configuration.rst

**Comment by rschwammborn** [comment]
New PR (which adds the resetroot command) has been merged into the new documentation release branch which will replace the current documentation soon.
