### ISSUE TITLE
Quickstart Buttons in Text are not displayed -  |mapbender3-button-add|,

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#186]
**Describe the bug**
In abstract https://doc.mapbender.org/de/quickstart.html#fugen-sie-elemente-zu-ihrer-anwendung-hinzu
it says

Wählen Sie Anwendungen --> mapbender-button-edit Editier-Button --> Layouts --> Button **|mapbender3-button-add|,** um eine Übersicht über die Mapbender-Elemente zu erhalten.

 |mapbender3-button-add| should show + image

Link to the bug if possible:
* in the documentation https://doc.mapbender.org/de/quickstart.html#fugen-sie-elemente-zu-ihrer-anwendung-hinzu
* or at GitHub f.e-: https://github.com/mapbender/mapbender-documentation/blob/master/de/quickstart.rst

**Versions (in which version of the documentation does the error occur):**
 - Mapbender: 3.0.8.5

**Comment by rschwammborn** [comment]
Fixed. :+1:
