### ISSUE TITLE
ImageLink in Documentation

### ISSUE THREAD

**Issue by VarCharly** [mapbender/mapbender-documentation#198]
Wrong link to images in german documentation of templates here: https://github.com/mapbender/mapbender-documentation/blob/master/de/customization/mapbender_templates.rst  

Change from 
"https://doc.mapbender.org/de/figures/sidepane_accordion.png"
to
"https://doc.mapbender.org/_images/sidepane_buttons.png"

**Comment by thzanger** [comment]
Hello @VarCharly, thanks for the information. A pull request has been opened for this issue.

**Comment by rschwammborn** [comment]
PR which includes the link fixes is ready for review: https://github.com/mapbender/mapbender-documentation/pull/197

**Comment by rschwammborn** [comment]
Changes which fix the broken file paths are now live!
