### ISSUE TITLE
Wrong Variables in "HTML-Element: Add variables into a HTMl-element"

### ISSUE THREAD

**Issue by VarCharly** [mapbender/mapbender-documentation#200]
**Describe the bug**
You can't use some of the examples for the html-variables in the newer mapbender versions. 
This works fine: `<p>Username: {{ app.user.username }}</p>`

This throws an error: `<p>Anwendung: {{ application.title }}</p>`
Error "Invalid content in Mapbender\CoreBundle\Element\HTMLElement caused Twig\Error\RuntimeError"

Link to the bug (de/en):
* in the documentation https://doc.mapbender.org/en/functions/misc/html.html#add-variables-into-a-html-element
* or at GitHub f.e-: https://github.com/mapbender/mapbender-documentation/blob/master/en/functions/misc/html.rst

**Version:**
 - Mapbender: 3.2.1
- Symfony 3.4.43
- PHP 7.2.33
- Windows 64

**Improvement**
Update the variables (not working) and set new examples in the documentation. I would like to display the name of my application in my application frontend...

**Comment by werrolf** [comment]
Fixed in [Mapbender commit b1f6bcb](https://github.com/mapbender/mapbender/commit/b1f6bcbc3c99dec6eac619cf457cfce2fb625661), will be in next version.

**Comment by VarCharly** [comment]
Thanks! 
This works fine for me 😚
