### ISSUE TITLE
Customization/ Tipps and tricks - Pages partly hidden in sidepane

### ISSUE THREAD

**Issue by thzanger** [mapbender/mapbender-documentation#203]
**Describe the bug:**
There is a certain page in the section "Customization/ Tipps and tricks" which hides the following pages in the sidepane if you try to open it. Additionally a new page comes up in the sidepane.

To reproduce go to "Customization/ Tipps and tricks". This chapter consists of five different sections. Now click on the section: "How to change the style of your application with the css-editor?". The two following pages (YAML Config...., app/ console commands) have now disappeared in the sidepane. I have to go back to Customization/ Tipps and tricks in order to see them. Additionally a new page called "Database Configuration" has come up. 

Link to the bug if possible:
* in the documentation [https://doc.mapbender.org/en/customization.html](url)
* or at GitHub f.e-: [https://github.com/mapbender/mapbender-documentation/tree/master/en/customization](url)

**Versions:**
Documentation: 3.0.8 (EN)
Browser: Firefox and Chromium

**Improvement**
No pages should disappear in the sidepane.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/67112568/95856510-6ce38580-0d5a-11eb-89f0-38153799e4cb.png)
![grafik](https://user-images.githubusercontent.com/67112568/95856539-7836b100-0d5a-11eb-8f0d-b6a163d79c14.png)

**Comment by rschwammborn** [comment]
This indeed is a strange problem: I also noticed a really similar behavior in the section "Installation" (both languages, but different subpages. German version: Git page; English version: Update/Symfony pages). It seems to change to a earlier TOC - structure if you head to certain pages. I tried fixing this via file naming (see PR above), because I found some inconsistencies there.

**Comment by rschwammborn** [comment]
PR #204  wurde in release/3.2.0 gemerged, ich schließe dieses zugehörige Issue. Falls der Fehler dennoch bestehen sollte, kann es wieder geöffnet werden.
