### ISSUE TITLE
[printclient] add documentation about passing logged in username to pdf output via user_name 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#210]
**Describe your feature request**
New feature: You can define **user_name** in your odg print template. If user_name is defined for logged in users the Username is printed in the pdf at the defined location. If you are not logged in no user_name is printed.

Great feature! Could be added to the documentation of Mapbender 3.2

**Additional context**

**Screenshots**
![Bildschirmfoto von 2020-11-19 15-42-52](https://user-images.githubusercontent.com/996298/99685403-d7d35b00-2a82-11eb-9303-a0c062ef29c0.png)

![Bildschirmfoto von 2020-11-19 15-43-58](https://user-images.githubusercontent.com/996298/99685428-dd30a580-2a82-11eb-8462-9997fb180c5f.png)

**Comment by thzanger** [comment]
Thank you for this information. A PR has been opened in this regard (#211)

**Comment by rschwammborn** [comment]
PR has been merged and is now part of the new upcoming Mapbender documentation.
