### ISSUE TITLE
[Digiitizer] type: breakLine has to be written with L upper Case

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#234]
**Describe the bug**
type: breakLine has to be written with L upper Case. With lower case you do not get the breakline (3.0.8.6 & 3.2.x)

Link to the bug if possible:
* in https://doc.mapbender.org/en/functions/editing/digitizer.html#breaklines-type-breakline

**Versions (in which version of the documentation does the error occur):**
 - Mapbender: 3.0.8.6 docu. 2021-04-14

**Comment by rschwammborn** [comment]
Fixed, see PR above.
