### ISSUE TITLE
Search Router and further funcionality questions ^^

### ISSUE THREAD

**Issue by MathewNWSH** [mapbender/mapbender-documentation#318]
Hello there,

I have recently started my adventure with Mapbender. From here I wanted to congratulate you for doing a good job in providing free geoprocessing solutions.

While creating the geportal I encountered a problem. I would like to add a Search Router to my geportal but I am having trouble connecting to a PostgreSQL database. Is it enough if I change database properties in config parameters.yml file to properties of my database and then define what I want to search in the Contents tab?

I also have a question about defining checkboxes in Mapbender. I would like to create a feature using FeatureInfo that displays a graph created based on data from columns in the database, but the graphs in the image would only come from columns whose names are marked with chechboxes. Could you please tell me how I could achieve this functionality and what I need to learn to do it?

**Comment by astroidex** [comment]
Hello @MathewNWSH, if you have questions about Mapbender please refer to the mailing list. You are welcome to ask your question there. 
Mailing list
https://lists.osgeo.org/mailman/listinfo/mapbender_users

You can also check the mapbender-workshop where you find configuration examples
https://github.com/mapbender/mapbender-workshop
