### ISSUE TITLE
add more links

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#383]
interaction between the pages

**Comment by rschwammborn** [comment]
Issue #389 also refers to this and helps to add more interaction between quickstart and the element pages, which is a handy addition to the documentation and a good starting point for this issue.

**Comment by rschwammborn** [comment]
I'm closing this as it can be seen as done - there's new interaction with links to the elements in the quickstart. Plus, we have unified the structure with ` :ref: ` that makes it easier to provide links in the future.
