### ISSUE TITLE
new Permission system please update the screenshot and check the content 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#459]
**Describe your feature request**
- de/en versions please check and update screenshots
- https://docs.mapbender.org/develop/en/quickstart.html
- @astroidex need quickstart for FOSS4G Europe 2024 at  1. July
-

**Comment by rschwammborn** [comment]
First batch of work on this was done via #466 . I'll check some more text and come back to this again before deadline day.
