### ISSUE TITLE
Enhance parameters of gpsposition-element

### ISSUE THREAD

**Issue by atd-schubert** [mapbender/mapbender-documentation#6]
Add infos for the missing parameters in the [english](https://github.com/mapbender/mapbender-documentation/blob/develop/en/bundles/Mapbender/CoreBundle/elements/gpsposition.rst) and [german](https://github.com/mapbender/mapbender-documentation/blob/develop/de/bundles/Mapbender/CoreBundle/elements/gpsposition.rst) documentation.

Missing parameters:
* `centerOnFirstPosition`
* `zoomToAccuracy`
* `zoomToAccuracyOnFirstPosition`

**Comment by AxxL** [comment]
@atd-schubert Kann man das schließen?

**Comment by AxxL** [comment]
yepp.
