### ISSUE TITLE
How to contribute - add rules for bug reports/pull requests

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender-documentation#67]
I would suggest to add rules for bug reports and pull requests in the mapbender documentation or/and contributing guide: 
* new bullet point on main page at https://doc.mapbender.org/en/index.html
* something like this: https://docs.opendronemap.org/contributing.html#template-for-submitting-bug-reports or this: https://docs.opendronemap.org/contributing.html#pull-requests

**Comment by astroidex** [comment]
Good idea.
We could create bug-Ticket templates like for mapbender-tickets: https://github.com/mapbender/mapbender/tree/release/3.0.7/.github/ISSUE_TEMPLATE

**Comment by astroidex** [comment]
I created templates for bug and feature request and made a PR #85

**Comment by fhaefker** [comment]
After the review of #85, the documentation will be updated - thus I will close this issue
