### ISSUE TITLE
[Documentation] vendor specific - service configuration 

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender-documentation#68]
Add missing documentation for the vendor specific parameter in the layerset/ service configuration. Perhaps integration in existing sites: 
* https://github.com/mapbender/mapbender-documentation/blob/release/3.0.6/de/functions/backend/layerset.rst
* https://github.com/mapbender/mapbender-documentation/blob/release/3.0.6/en/functions/backend/layerset.rst

To-do: 
* transfer from existing documentation in quickstart
* show possibilities
* supported parameters
* screenhots
* examples with urls

**Comment by fhaefker** [comment]
Hello,
please recheck if action is required @CharlyUnicorn @philvanbwg

**Comment by philvanbwg** [comment]
Everything fine for 3.0.6. But for the 3.0.8 documentation this part about VSP needs to be worked over since the functionality has changed quite a bit.
