### ISSUE TITLE
Search Router: Increase information in Search Router

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender-documentation#69]
The Simple Search has some parameters, that are not documented yet.

Please validate and complete the Documentation.

Further assistance: @CharlyUnicorn

**Comment by fhaefker** [comment]
@ schuettler @ rschwammborn

Please check the information from @CharlyUnicorn

If necessary, please update the documentation accordingly

**Comment by rschwammborn** [comment]
Hi,
in my opinion, the missing points 1 & 2 are already included (maybe they were added in the meantime).

1.) There are several examples in the description texts / YAML comments that show where to put which field type for the search router configuration.
2.) For the autocomplete features, it's quite the same as in 1.): There is a advise in the section under "Konfigurationsbeispiele -> Beispiele" that shows that you don't have to type in the exact terms for autocompletion.

Considering 3.) & 4.), my advise would be that we don't include those tips in the user documentation anymore to minimize clutter. Users who are desperately searching for this information will find it typed out above in the initial comment. Moreover, there's still a mailing list for all complex problems considering Mapbender!
