### ISSUE TITLE
[Documentation] Make the database configuration in the yaml files a bit clearer

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender-documentation#72]
**Datenbankkonfiguration**

* Link zwischen der Datenbankverbindung mit Platzhaltern hervorheben/ erklären und mit Bild beide Dateien nebeneinander zeigen (parameters.yaml und config.yaml)

**Comment by fhaefker** [comment]
Dear @CharlyUnicorn

Do you still recommend such an improvement? If required, please send further information to @rschwammborn @ schuettler

**Comment by rschwammborn** [comment]
Since 08/2019 there is a page which explains this connection quite clearly (https://doc.mapbender.org/en/customization/yaml.html). While it doesn't have the side-by-side image representation, it still comes close with a default in-line example ;-)
