### ISSUE TITLE
[documentation] searchrouter configuration is in german not english

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#75]
* in the example blocks in the documentation the explanations are in german not in english

* current: https://docs.mapbender.org/current/en/functions/search/search_router.html
* in 3.0.6.3 they were still there https://docs.mapbender.org/3063/en/bundles/Mapbender/CoreBundle/elements/search_router.html

* explanation for "data-autocomplete-using" is missing or is only in german

**Comment by fhaefker** [comment]
@ rschwammborn @ schuettler
Please change the example of the English documentation to the correct language
