### ISSUE TITLE
Documentation - HTML Element

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender-documentation#76]
You can add a lot of information to your application via the html element (https://doc.mapbender.org/en/functions/misc/html.html). 
It would be nice to have more example definitions or a list of possible variables for the three values 
 “application” (Entity Application), “entity” (Entity HTMLElement) and “configuration”.

Like this: 
```
content: <p>Application Title: {{ application.title |trans }}</p>

content: <p>Logged in with: {{ app.user.username |trans }}</p>
```

**Comment by fhaefker** [comment]
@ rschwammborn @ schuettler

Please check if you can answer the question of @CharlyUnicorn
If necessary, contact the Mapbender team

**Comment by eschuettler** [comment]
@CharlyUnicorn 
I added some information about twig variables and examples with 'group.title' and 'app.user.username' to the documentation.
It won't work for 'template' and 'updated'.

**Comment by CharlyUnicorn** [comment]
@eschuettler thanks - i think this will help a lot.

**Comment by eschuettler** [comment]
@CharlyUnicorn you're welcome.
