### ISSUE TITLE
Navigation toolbar in Mapbender Mobile template 

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender-documentation#77]
If you add the navigation toolbar in your template you can activate the function "draggable" if you activate the regarding checkbox. 

If you do this in an application, that uses the "Mapbender Mobile template", then you can't drag the navigation toolbar. If you click on the "draggable-button" above toolbar this happens: 

![auswahl_015](https://user-images.githubusercontent.com/13517141/38253951-42a215a0-3758-11e8-960b-56cf8638ca49.png)

You can test this behaviour with any mobile application (tested with 3.0.6.3 version)

**Comment by fhaefker** [comment]
Dear @CharlyUnicorn

Please create a pull request according to your proposal

**Comment by thzanger** [comment]
Issue has been fixed. This ticket will therefore be closed.
