### ISSUE TITLE
[Documentation] please add information about how an application can switch to another language

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#78]
* see mailing list thread set language for one Application: mapbender-user. https://lists.osgeo.org/pipermail/mapbender_users/2018-February/005371.html
* suggestion by user Karsten

* How can application switch to another language (Title, Tooltip,)
* provide information about how to use the information from the translations-files

**Comment by fhaefker** [comment]
@rschwammborn @eschuettler 

Please check whether the information in the documentation corresponds to the information provided by Rolf. If not, please correct it yourself. You should check with Rolf whether it is stil the case in Mapbender 3.0.8.x
