### ISSUE TITLE
Improve Mapbender installation page

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#86]
* actual documentation refers to php5 (and at the bottom to PHP7) -> confusing
* https://github.com/mapbender/mapbender-documentation/blob/407132d44d858ae68b583928886592c67b29045b/en/installation/installation_ubuntu.rst

**Improvement**
Transfer description about PHP7 to the top

**Comment by fhaefker** [comment]
@rschwammborn  @eschuettler 

Please change the documentation according to the recommendation of @astroidex
