### ISSUE TITLE
graphical representation of the version history

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender-documentation#89]
Hello,
in several trainings the desire was expressed to provide a **graphical representation of the version history in the documentation**.
In addition, the specification of the supported PHP version, OpenLayers and Symfony should also appear.

The first template for this specification would be the table below - inspired by the very nice PHP documentation at https://www.gambio.de/blog/wp-content/uploads/Schnappschuss_080818_013508_PM.jpg and https://de.wikipedia.org/wiki/Versionsgeschichte_von_PHP

![version_mb](https://user-images.githubusercontent.com/13517141/57845998-884c0900-77d3-11e9-97af-b440a80c9bd6.png)

My suggestion would be to reduce the current documentation page (redundant information from the changelog in versions.rst) and for that use only the link to the changelog and this graphic table. Perhaps we can add more informations or display the facts in a better way?

**Further important information:**
* currently supported version is 3.0.8.x
* PHP 5.6 to 7.1 compatible
* Symfony 2.8 and OpenLayers 2 in action
* when switching to 3.1, Symfony 3.x and OpenLayers 4 will be used
* more information about versions can be found at https://github.com/mapbender/mapbender-starter/blob/master/CHANGELOG.md

**Suggestion ToDo:**
* remove redundant infos in https://github.com/mapbender/mapbender-documentation/blob/master/en/versions.rst and /de/versions.rst
* add graphic to versions.rst
* update the infos with every release (not so much work...) in table:  
[versions_mapbender.zip](https://github.com/mapbender/mapbender-documentation/files/3186559/versions_mapbender.zip)

**Comment by CharlyUnicorn** [comment]
@fhaefker 
@werrolf 
@astroidex 
@kartoffelfee 

maybe you also have ideas for visualization?

**Comment by CharlyUnicorn** [comment]
Documentation about supported php which is important: 

The Doctrine version, which is officially included with the Mapbender, does not have full support for PostgreSQL 10. The error manifests itself in doctrine:schema:update as an error, where a 'min_value' of a sequence is selected. The schema can not be updated.

The Doctrine version with PostgreSQL 10 support needs PHP 7.1. If you're sure that you have PHP 7.1 or higher, and you want to use Postgres 10, you can set the PHP Platform requirement to PHP 7.1 in application / composer.json and then manually update Doctrine as follows:
$ bin/composer update --with-dependencies doctrine/dbal doctrine/common doctrine/doctrine-bundle

The entire PHP 5er series has not been maintained since January - PHP 7.0 ends at the end of the year.

**Comment by fhaefker** [comment]
Hi @CharlyUnicorn 

This idea is incredible - we will work on it

**Comment by astroidex** [comment]
sorry. we do not work on this.  We only provide https://github.com/mapbender/mapbender-starter/blob/master/CHANGELOG.md
