### ISSUE TITLE
Add documentation about the Disclaimer

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#90]
* from 3.0.8.1 you can define a disclaimer 
* transfer the documentation from the PR to the normal documentation. Add an example to parameters.yml (# auskommentiert)
* see https://github.com/mapbender/mapbender/pull/1158

* https://github.com/mapbender/mapbender-starter/blob/master/application/app/config/parameters.yml.dist

**Comment by fhaefker** [comment]
@eschuettler @rschwammborn 

Please inquire with Philipp K about the information required to create documentation
