### ISSUE TITLE
[PrintClient] Transfer docmentation of new configuration to print documentation

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender-documentation#92]
* printClient changed in version 3.0.8
* there are new possibilities for configuration
* https://github.com/mapbender/mapbender/blob/v3.0.8.1/src/Mapbender/PrintBundle/CONFIGURATION.md

**Comment by fhaefker** [comment]
@rschwammborn @eschuettler 

please create a pull request accordingly
