### ISSUE TITLE
PDF-Export/Download 

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender-documentation#98]
it would be nice if you could download the documentation in the current version as a pdf (use it offline, print docu, share version). we could add a link at the main page...

e.g. with qgis: 
- https://www.qgis.org/en/docs/index.html
- https://docs.qgis.org/3.4/pdf/en/QGIS-3.4-UserGuide-en.pdf

**Comment by fhaefker** [comment]
Thanks for the suggestion :)

We will create such a PDF in due course. However, we are currently revising all the documentation to bring it up to date. Therefore, we will wait with the creation of a downloadable document until we have a better state of the manual.

**Comment by pwheregroup** [comment]
Hey folks,

the PDF export is now available. Please see: https://doc.mapbender.org where you can see the download in both languages (german and english).
Credits go out to philipp who made the creation possible on the server.

@CharlyUnicorn @fhaefker please have a look and give suitable feedback.
Hope you enjoy and have fun!

Appendix:
1: "Therefore, we will wait with the creation of a downloadable document until we have a better state of the manual."
On 1: The creation is independent from the state or the structure of the document. Therefore you dont need to worry (mostly) about compatibility in the future releases.

**Comment by astroidex** [comment]
Great. Thanks a lot looks good. Should we send the information on the mailing list?
